service: labs-aws-image-analysis
package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}

functions:
  create:
    handler: src/recognition/image/index.handler
    events:
      - http:
          path: analyse/image
          method: get

custom:
  webpack:
    webpackConfig: 'webpack.config.js'
    packager: 'npm'
    includeModules: true
